from __future__ import annotations


TIER1_AMOUNT_TOLERANCE = 0.01  
TIER1_MAX_NORMAL_LAG_DAYS = 2  

TIER2_AMOUNT_TOLERANCE_MIN = 1.0  
TIER2_AMOUNT_TOLERANCE_MAX = 50.0 
TIER2_AMOUNT_EXACT_ISH = 0.50  
TIER2_MAX_LATE_LAG_DAYS = 18  
TIER2_LAG_EXACT_ISH_DAYS = 2  

TIER2_LAG_REALISTIC_MIN_OVERSHOOT_DAYS = 4 

POSTING_LAG_MAX_DAYS = 2  

TIER3_DATE_WINDOW_DAYS = 14
TIER3_MAX_POOL_SIZE = 40  
TIER3_AMOUNT_TOLERANCE = 50.0  
TIER3_MAX_SUBSET_SIZE = 40  
SUBSET_SUM_CENTS_SCALE = 100  

TIER1_CONFIDENCE = 1.0
TIER3_BASE_CONFIDENCE = 0.85  

TIER3_SINGLE_INVOICE_PENALTY = 0.5

AUTO_MATCH_MIN_CONFIDENCE = 0.7

REVIEW_QUEUE_MIN_CONFIDENCE = 0.45

ORPHAN_RULE_CONFIDENCE = 0.9

LLM_MODEL = "claude-opus-5"
LLM_MAX_TURNS = 4  
LLM_MAX_TOKENS = 4096  
LLM_INPUT_COST_PER_MTOK = 5.0
LLM_OUTPUT_COST_PER_MTOK = 25.0

GROQ_MODEL = "openai/gpt-oss-120b"

GROQ_TPM_LIMIT = 7000

GROQ_ACCOUNT_TPM_LIMIT = 8000

GROQ_INPUT_COST_PER_MTOK = 0.15
GROQ_OUTPUT_COST_PER_MTOK = 0.60
